[CmdletBinding(SupportsShouldProcess)]
param([string]$Path = (Get-Location).Path, [switch]$RemoveClaudeMd)

$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path -LiteralPath $Path).Path
if (-not (Test-Path -LiteralPath (Join-Path $repo '.git'))) { throw "Not a Git repository: $repo" }

# Detect via ANY known artifact, not covenant_state.json alone (it's gitignored in
# most target repos) - mirrors CovenantMac's uninstall.sh _governed_repo_detected.
$markers = @('.githooks\covenantwin.py', '.claude\covenant_state.json', '.claude\hooks\pre_bash_trust_root_guard.sh', '.claude\covenant_integrity.sha256')
$found = $false
foreach ($m in $markers) { if (Test-Path -LiteralPath (Join-Path $repo $m)) { $found = $true; break } }
if (-not $found) { throw "No governed repo detected in $repo (checked $($markers -join ', ')). Nothing to remove." }

$hookPath = (& git -C $repo config --get core.hooksPath 2>$null)
if ($hookPath -eq '.githooks') { & git -C $repo config --unset core.hooksPath }
& git -C $repo config --unset-all remote.origin.push 'refs/notes/bypasses:refs/notes/bypasses' 2>$null
& git -C $repo config --unset-all remote.origin.fetch '\+refs/notes/bypasses:refs/notes/bypasses' 2>$null

# Dev guide / init package (either basket) - real, human-onboarding-relevant
# copies CovenantWin wrote at install time; CovenantMac removes these unconditionally
# too (they're framework-owned content, not human-authored).
foreach ($f in @('v1_claude_code_development_guide_new.md','v1_claude_code_development_guide_existing.md',
                 'v1_implementation_package_new.md','v1_implementation_package_existing.md')) {
  $target = Join-Path $repo $f
  if ((Test-Path -LiteralPath $target) -and $PSCmdlet.ShouldProcess($target, 'Remove CovenantWin-generated artifact')) {
    Remove-Item -LiteralPath $target -Force
  }
}

# .githooks/ and the entire .claude/ tree (covenant_state.json, baseline.json,
# hooks/, commands/, checkpoints/, covenant_integrity.sha256, settings.json) -
# framework-owned, same blanket-removal philosophy as CovenantMac's uninstall.sh.
foreach ($relative in @('.githooks', '.claude')) {
  $target = Join-Path $repo $relative
  if ((Test-Path -LiteralPath $target) -and $PSCmdlet.ShouldProcess($target, 'Remove CovenantWin-generated artifact')) {
    Remove-Item -LiteralPath $target -Recurse -Force
  }
}

# CI workflow - only if it's actually the one CovenantWin wrote (never touch an
# unrelated workflow a human placed at the same path), same conditional
# removal CovenantMac's uninstall.sh applies.
$ciWorkflow = Join-Path $repo '.github\workflows\covenant.yml'
if (Test-Path -LiteralPath $ciWorkflow) {
  $ciContent = Get-Content -LiteralPath $ciWorkflow -Raw
  if ($ciContent -match 'covenantwin\.py' -and $PSCmdlet.ShouldProcess($ciWorkflow, 'Remove CovenantWin-generated artifact')) {
    Remove-Item -LiteralPath $ciWorkflow -Force
  }
}

# .gitignore entries added by install.ps1
$gitignorePath = Join-Path $repo '.gitignore'
if (Test-Path -LiteralPath $gitignorePath) {
  $entries = @('.claude/session_state.json', '.claude/session_spend.tmp', '.claude/git_cache.json', '.claude/checkpoints/')
  $lines = Get-Content -LiteralPath $gitignorePath
  $kept = $lines | Where-Object { $entries -notcontains $_.Trim() }
  if (($kept -join "`n") -ne ($lines -join "`n")) {
    if ($PSCmdlet.ShouldProcess($gitignorePath, 'Remove CovenantWin .gitignore entries')) {
      Set-Content -LiteralPath $gitignorePath -Value $kept -Encoding utf8
    }
  }
}

# .gitattributes entries added by install.ps1 (pins the 4 governance files to
# LF so a common Windows git config, core.autocrlf=true, can't silently
# rewrite their bytes on checkout and break the integrity manifest)
$gitattributesPath = Join-Path $repo '.gitattributes'
if (Test-Path -LiteralPath $gitattributesPath) {
  $gaEntries = @(
    '.githooks/covenantwin.py text eol=lf',
    '.githooks/pre-commit text eol=lf',
    '.githooks/pre-push text eol=lf',
    '.claude/hooks/pre_bash_trust_root_guard.sh text eol=lf'
  )
  $gaLines = Get-Content -LiteralPath $gitattributesPath
  $gaKept = $gaLines | Where-Object { $gaEntries -notcontains $_.Trim() }
  if (($gaKept -join "`n") -ne ($gaLines -join "`n")) {
    if ($PSCmdlet.ShouldProcess($gitattributesPath, 'Remove CovenantWin .gitattributes entries')) {
      Set-Content -LiteralPath $gitattributesPath -Value $gaKept -Encoding utf8
    }
  }
}

# .github/CODEOWNERS is intentionally NEVER removed here - same as CovenantMac's
# uninstall.sh: a human may have already replaced the placeholder team with
# real content, and this uninstaller removes governance tooling, not repo
# configuration a human has taken ownership of.

# CLAUDE.md - generated by Claude Code during /init-governance and likely
# contains real, human-approved architectural decisions by now. CovenantMac's
# uninstall.sh gives this a separate interactive confirmation; this script
# instead requires the explicit -RemoveClaudeMd switch (avoids a Read-Host
# prompt that would make this uninstaller impossible to script/test), and
# defaults to keeping it.
$claudeMd = Join-Path $repo 'CLAUDE.md'
if (Test-Path -LiteralPath $claudeMd) {
  if ($RemoveClaudeMd -and $PSCmdlet.ShouldProcess($claudeMd, 'Remove CLAUDE.md')) {
    Remove-Item -LiteralPath $claudeMd -Force
  } else {
    Write-Host "Kept: CLAUDE.md (repo constitution, likely human-approved) - pass -RemoveClaudeMd to remove it too."
  }
}

Write-Host "CovenantWin removed from $repo."
